import mongoose from "mongoose";

const itemSchema = new mongoose.Schema({
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "users",
        required: true
    },
    // Source information
    url: {
        type: String,
        require: true,
        default: null
    },

    // Content metadata
    title: {
        type: String,
        require: true,
        default: []
    },
    description: String,
    tags: [String],   // Generated by AI
    image: String,
    siteName: String,

    // Content
    content: String,     // Extracted text from article/pdf
    contentType: {
        type: String,
        enum: ["article", "tweet", "image", "video", "pdf", "file", "other"],
        default: 'other'
    },

    // File (If user uploaded)
    file: {
        storagePath: String,
        fileUrl: String,
        mimeType: String,
        fileSize: Number,
        originalFileName: String
    },

    // Search & recomendations
    chromaId: {
        type: String,
        sparse: true
    },

    collectionId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "collection"
    },

    // Resurfacing 
    lastResurfaceDate: Date,
    resurfaceCount: {
        type: Number,
        default: 0
    },
    topicClusterId: String,
    topicLabel: String,
    status: {
        type: String,
        enum: ["queued", "processing", "ready", "failed"],
        default: "queued"
    },
    lastProcessingAt: Date,
    processingAttempts: {
        type: Number,
        default: 0
    },
    processingError: {
        type: String,
        default: null
    },
    sourceFingerprint: String,
    contentFingerprint: String,
    duplicateOf:    {
        type: mongoose.Schema.Types.ObjectId,
        ref: "items",
        default: null
    }

}, { timestamps: true })

itemSchema.index({ userId: 1, sourceFingerprint: 1 })
itemSchema.index({ userId: 1, contentFingerprint: 1 })

export const itemModel = mongoose.model("items", itemSchema)
